### ISSUE TITLE
``sonar.jqassistant.reportPath`` for maven multi module configuration

### ISSUE THREAD

**Issue by mmoossen** [jqassistant-contrib/sonar-jqassistant-plugin#10]
Hi,

we got a maven multi-module project, were the jqa rules of module1 have nothing to do with the jqa rules of module2 nor those of the aggregator project.

the `maven-jqassistant-plugin` works, imho, as expected. it uses by default `${project.build.directory}/xxx` which is module aware. for instance:
```
[INFO] --- jqassistant-maven-plugin:1.7.0:scan (scanAndAnalyse) @ module1 ---
[INFO] Loaded jQAssistant plugins [CDI, Common, Core Analysis, Core Report, EJB3, GraphML, JAX-RS, JPA 2, JSON, JUnit, Java, Java 8, Java EE 6, Maven 2 Repository, Maven 3, OSGi, RDBMS, Spring, TestNG, Tycho, XML, YAML].
[INFO] Connecting to store at 'file:/K:/repos/git/test/target/jqassistant/store/'
[INFO] Initializing embedded Neo4j server 3.x
[INFO] Resetting store.
[INFO] Reset finished (removed 0 nodes, 0 relations).
[INFO] Entering K:/repos/git/test/module1/target/classes
[INFO] Leaving K:/repos/git/test/module1/target/classes (382 entries, 1351 ms)
[INFO] Entering K:/repos/git/test/module1/target/test-classes
[INFO] Leaving K:/repos/git/test/module1/target/test-classes (230 entries, 590 ms)
[INFO] Entering K:/repos/git/test/module1/target/surefire-reports
[INFO] Leaving K:/repos/git/test/module1/target/surefire-reports (104 entries, 548 ms)

```
but `sonar-jqassistant-plugin` uses a hardcoded path(`target/jqassistant/jqassistant-report.xml`) in the property `sonar.jqassistant.reportPath`, and reads for every module the same report from the aggregator project:
```
[INFO] ------------- Run sensors on module Test Module1 develop
...
[INFO] Sensor JQA [jqassistant]
[INFO] Using project path 'K:\repos\git\test'.
[INFO] Found jQAssistant report at 'K:\repos\git\test\target\jqassistant\jqassistant-report.xml'.
...
[INFO] ------------- Run sensors on module Test Parent develop
[INFO] Sensor JQA [jqassistant]
[INFO] Using project path 'K:\repos\git\test'.
[INFO] Found jQAssistant report at 'K:\repos\git\test\target\jqassistant\jqassistant-report.xml'.
[INFO] Sensor JQA [jqassistant] (done) | time=7ms
...
```

if i set the property `sonar.jqassistant.reportPath` to use module aware paths, like `${project.build.directory}/jqassistant/jqassistant-report.xml`, in the sonar server configuration page, then the Maven variable does not get evaluated:

```
[INFO] No report found at 'K:\repos\git\test\${project.build.directory}\jqassistant\jqassistant-report.xml', skipping.
```

if i set the property `sonar.jqassistant.reportPath` to use module aware paths, like `${project.build.directory}/jqassistant/jqassistant-report.xml`, now in the pom.xml-files then i guess it will work in linux, but in Windows the path it wrongly recognized as a relative path, and everything gets messed up:

```
[INFO] ------------- Run sensors on module AuV develop
[INFO] Sensor JQA [jqassistant]
[INFO] Using project path 'K:\repos\git\test'.
[INFO] No report found at 'K:\repos\git\test\K:\repos\git\test\target\jqassistant\jqassistant-report.xml', skipping.
```

any help greatly appreciated.

Michael

**Comment by DirkMahler** [comment]
You ran into a limitation of the current implementation. The semantics of the sonar.jqassistant.reportPath property has been "sharpened" now:

* If not given, the file will be searched in the target directory of the project root (treating the whole reactor as one project)
* If given as relative path it will be looked up based on the current module directory
* If given as absolute path then it will be used as such

For your setup this would mean that in your parent pom.xml you can declare the property using a relative path `target/jqassistant/jqassistant-report.xml`.

Can you verify using the latest SNAPSHOT from https://oss.sonatype.org/content/repositories/snapshots/org/jqassistant/contrib/sonarqube/sonar-jqassistant-plugin/1.8.0-SNAPSHOT/? If this works a 1.7.3 release can be provided soon.

**Comment by mmoossen** [comment]
Hi Dirk,
sorry for the late reply.
many thanks for your prompt help.
now it is working! using snapshot 20191222
just one small point:
the parameter says that it has the default value: "target/jqassistant/jqassistant-report.xml", but if not set, then it works as before, relative to the project root and not the module root. 
only when setting it explicitly to target/jqassistant/jqassistant-report.xml it works as needed in my case. i.e. relative to the module root.
may be the label for the default value is not accurate any more?
wishing you nice and peaceful holidays

**Comment by DirkMahler** [comment]
I've updated the description for the property, saying that the default value is relative to the project root. Will be delivered with the next release.

**Comment by DirkMahler** [comment]
Nevertheless: thanks for the feedback and wishing you all peaceful holidays and a good start into 2020 as well!
