### ISSUE TITLE
Possibility to create SonarQube Bugs instead of Code Smells

### ISSUE THREAD

**Issue by Flow-Devel** [jqassistant-contrib/sonar-jqassistant-plugin#13]
I am looking for a possibility to create SonarQube Bugs instead of Code Smells.

SonarQube has no possibility to fail a Quality-Gate by a single rule. Our architecture violations get lost between the other Code Smells and nobody cares.

The most flexible way would be to decide what type of Issue should be created per rule (or Severity?). An easier to achieve approach could be to create two new Rules with the type Bug in the SonarQube-Repo. Everybody could choose in SonarQube to use the Code Smell rule or the Bug rule.

**Comment by DirkMahler** [comment]
For clarification: the user should be able to decide, whether all violations reported by jQA shall be reported either as code smell or bug? 

If so I'd propose to introduce a property for the SQ plugin, e.g. `sonar.jqassistant.issueType` taking `CODE_SMELL` (default) or `BUG` (case-insensitve) as values.
From the SQ API there would as well be `VULNERABILITY` or `SECURITY_HOTSPOT` available but that doesn't make sense for a setting affecting all rules. Maybe we can extend this later to a per-rule-setting with the configurable default.

**Comment by DirkMahler** [comment]
The jQAssistant configuration now provides an option to select the issue type to create:

![grafik](https://user-images.githubusercontent.com/437925/122682645-0a9d2780-d1fb-11eb-8113-d70694440769.png)
