### ISSUE TITLE
Low Performance after Version Update

### ISSUE THREAD

**Issue by Flowdevel** [jqassistant-contrib/sonar-jqassistant-plugin#15]
We updated our SonarQube version from 8.4 to 9.9 and JQAssistant from 1.9 to 1.12. After that the time of our SonarQube analysis increased from 20 to 33 Minutes. After disabling the JQAssistant scanner in SonarQube time dropped to 10 Minute.

We have a multi-module build with 188 projects and one JQAssistant analysis for the complete reactor. After the update the size of the report file increases from 180 to 240 MB. The analysis time from the SonarQube Plugin increased from 4000ms to 8000ms for each module. The 8000ms for every 188 Projects leads to 25 minutes in total.

I tried to change the behavior of the plugin by only reading the report once and store in a static variable. That works fine for our build. 
At the moment I don´t handle different configuration, like one report for each module.

Would it be possible to cache the Report?

**Comment by DirkMahler** [comment]
The plugin has been changed such that once imported jQAssistant XML report files are now cached. A bugfix release will be made available during the next days.

**Comment by Flowdevel** [comment]
Works great! The time of our SonarQube analyze decreased from 34 to 11 minutes. Thank you.

**Comment by DirkMahler** [comment]
Thanks for the feedback! Will then trigger the release this week.

**Comment by DirkMahler** [comment]
The release has been built as 1.12.1 and [requested](https://community.sonarsource.com/t/new-release-jqassistant-1-12-1/86023) to be published to the SQ marketplace.

**Comment by DirkMahler** [comment]
> The release has been built as 1.12.1 and [requested](https://community.sonarsource.com/t/new-release-jqassistant-1-12-1/86023) to be published to the SQ marketplace.

It's now available in the marketplace.
