### ISSUE TITLE
Improved support for Maven multi module projects

### ISSUE THREAD

**Issue by DirkMahler** [jqassistant-contrib/sonar-jqassistant-plugin#4]
Currently the linking of issues to source code elements (e.g. classes) is not or only working in a limited way for Maven multi module projects.
The reason behind this is that jQA creates a global XML report of the analysis in the root module of a project. The SonarQube plugin evaluates the report in the context of this module but does not have access to the sources in sub-modules.

**Comment by anurzhanova** [comment]
It is impossible to create individual jqassistant-report.xml files if called together with the _useExecutionRootAsProjectRoot=true_ parameter in jqassistant:analyze. And without this parameter, the following error appears during jqassistant:analyze


> Failed to execute goal com.buschmais.jqassistant:jqassistant-maven-plugin:1.6.0:analyze (default-cli) on project xxx: Execution default-cli of goal com.buschmais.jqassistant:jqassistant-maven-plugin:1.6.0:analyze failed: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, xxx\jqassistant-shared\store: Component 'org.neo4j.kernel.internal.locker.StoreLockerLifecycleAdapter@24bf653d' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to obtain lock on store lock file: xxx\jqassistant-shared\store\store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)". -> [Help 1]

**Comment by DirkMahler** [comment]
@anurzhanova This store problem occurs if the jQA Maven plugin is executed in different modules with different class loaders ("interference" with other Maven plugins). Have you tried to declare the jQA Maven plugin with &lt;extensions&gt;true&lt;/extensions&gt;?

```
<plugin>
  <groupId>com.buschmais.jqassistant</groupId>
  <artifactId>jqassistant-maven-plugin</artifactId>
  <version>1.6.0</version>
  <extensions>true</extensions>
</plugin>
...
```
Nevertheless multi-module support needs to be fixed for the SQ plugin.

**Comment by anurzhanova** [comment]
@DirkMahler thanks for the solution. It worked after I changed parameter  _storeLifecycle_ to _MODULE_. 

> Nevertheless multi-module support needs to be fixed for the SQ plugin.

Yes, I unfortunately still have a lot of problems with the visualization of constraints in SonarQube.

**Comment by DirkMahler** [comment]
@DanielKraft @saschagrebe This feature has been implemented based on #5, could you verify if the current code in the branch feature/multi-module still works for you?

**Comment by DanielKraft** [comment]
@DirkMahler Sorry for the late reply. The 1.7.0 release still works for us.

**Comment by DirkMahler** [comment]
@DanielKraft Thanks for the feedback!
