### ISSUE TITLE
Support for LTS 7.9

### ISSUE THREAD

**Issue by saschagrebe** [jqassistant-contrib/sonar-jqassistant-plugin#5]
The Plugin is not compatible with the new LTS version of SonarQube anymore. Is support planed?

**Comment by DanielKraft** [comment]
#6 This should make the plugin compatible again.

**Comment by saschagrebe** [comment]
@DirkMahler 
It looks like MSG does not maintain the plugin anymore. One of my colleagues at adesso made a pull request. Can you review it and release a new version?

**Comment by DirkMahler** [comment]
@saschagrebe I've forwarded this to msg for approving the PR, asking for a little more patience.

**Comment by DirkMahler** [comment]
PR has been merged.
